[linters-settings.errcheck]
check-type-assertions = true

[linters-settings.goconst]
min-len = 2
min-occurrences = 3

[linters-settings.gocritic]
enabled-tags = [
  "diagnostic",
  "experimental",
  "opinionated",
  "performance",
  "style"
]

[linters-settings.govet]
check-shadowing = true
enable = [ "fieldalignment" ]

[linters-settings.nolintlint]
require-explanation = true
require-specific = true

[linters-settings.gosec]
excludes = [ "G201", "G204" ]

[issues]
include = [ "EXC0001", "EXC0005", "EXC0011", "EXC0012", "EXC0013" ]

[linters]
disable-all = true
enable = [
  "bodyclose",
  "cyclop",
  "errcheck",
  "exportloopref",
  "goconst",
  "gofumpt",
  "goimports",
  "gosec",
  "gosimple",
  "nilerr",
  "predeclared",
  "rowserrcheck",
  "sqlclosecheck",
  "staticcheck",
  "tparallel",
  "misspell",
  "unconvert",
  "unparam",
  "unused",
  "whitespace",
  "unconvert",
  # "revive",
]

[run]
issues-exit-code = 1
