issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013
linters:
  disable-all: true
  enable:
    # - cyclop
    - dupl
    - err113
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - funlen
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - ineffassign
    - interfacebloat
    - lll
    - makezero
    - misspell
    # - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck
    - tagalign
    # - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
run:
  tests: true
  issues-exit-code: 1
output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude: ""
    exclude-functions: []
  nlreturn:
    block-size: 3
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: false
    require-specific: true
  gosec:
    excludes:
      - G201
      - G204
  errorlint:
    errorf: true
    asserts: false
    comparison: false
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: unexported-return
      - name: errorf
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: empty-block
      - name: confusing-naming
      - name: unnecessary-stmt
      - name: struct-tag
      - name: modifies-value-receiver
      - name: bool-literal-in-expr
      - name: early-return
      - name: unexported-naming
      - name: nested-structs
